/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.frontend;

import hotelelbuendescanso.BaseDatos;
import java.awt.Color;
import java.awt.Dimension;
import project.menu.frontend.DeshabilitadorMenu;
import project.menu.frontend.ModificadorMenu;
import project.alojamiento.frontend.RegistradorAlojamiento;
import project.alojamiento.frontend.ReporteAlojamientos;
import project.alojamiento.frontend.ReporteAlojamientosCliente;
import project.alojamiento.frontend.ReporteAlojamientosHabitacion;
import project.cliente.frontend.ModificadorCliente;
import project.menu.frontend.ReporteMenu;
import project.cliente.frontend.RegistradorCliente;
import project.cliente.frontend.ReporteClientes;
import project.habitacion.frontend.ModificadorPrecio;
import project.menu.frontend.CreadorMenu;
import project.menu.frontend.TomarPedido;
import project.reservacion.frontend.CanceladorReservacion;
import project.reservacion.frontend.RegistradorReservacion;
import project.reservacion.frontend.ReporteReservaciones;
import project.usuario.Usuario;
import project.usuario.frontend.CreadorUsuario;
import project.usuario.frontend.EliminadorUsuario;
import project.usuario.frontend.ModificadorUsuario;
import project.usuario.frontend.ReporteUsuarios;
import project.usuario.frontend.SolicitadorUsuario;

/**
 *
 * @author fabricio
 */
public class HotelDescktop extends javax.swing.JFrame {

    private BaseDatos DB = null;
    private Usuario usuario = null;

    /**
     * Creates new form HotelDescktop
     */
    public HotelDescktop(Usuario usr, BaseDatos DB) {
        this.usuario = usr;
        this.DB = DB;
        initComponents();
        this.setLocationRelativeTo(this);
        modificarItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        PrincipalDesktop = new javax.swing.JDesktopPane();
        labelInformacion = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        jMenuGerente = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCrearUsuario = new javax.swing.JMenuItem();
        jMenuItemReporte = new javax.swing.JMenuItem();
        jMenuItemModificar = new javax.swing.JMenuItem();
        jMenuItemEliminar = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemCrearMenu = new javax.swing.JMenuItem();
        jMenuItemRepMenu = new javax.swing.JMenuItem();
        jMenuItemModMen = new javax.swing.JMenuItem();
        jMenuItemDeshaMenu = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItemModPre = new javax.swing.JMenuItem();
        jMenuRecepcion = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemRegistrar = new javax.swing.JMenuItem();
        jMenuItemElimRes = new javax.swing.JMenuItem();
        jMenuItemReportReser = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemRegAloj = new javax.swing.JMenuItem();
        jMenuItemRepAloj = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItemAlojHab = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemRegClie = new javax.swing.JMenuItem();
        jMenuItemModClie = new javax.swing.JMenuItem();
        jMenuItemRepClie = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuRestaurante = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItemTomarPed = new javax.swing.JMenuItem();
        jMenuOpciones = new javax.swing.JMenu();
        jMenuItemCambiar = new javax.swing.JMenuItem();
        jMenuItemSalir = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelInformacion.setBackground(new java.awt.Color(254, 254, 254));
        labelInformacion.setFont(new java.awt.Font("Caviar Dreams", 1, 14)); // NOI18N
        labelInformacion.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(552, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(PrincipalDesktop)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelInformacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PrincipalDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuGerente.setText("Gerente");
        jMenuGerente.setVisible(false);

        jMenu1.setText("Usuario");

        jMenuItemCrearUsuario.setText("Crear Usuario");
        jMenuItemCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCrearUsuario);

        jMenuItemReporte.setText("Reporte Usuarios");
        jMenuItemReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReporteActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemReporte);

        jMenuItemModificar.setText("Modificar Usuario");
        jMenuItemModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModificarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemModificar);

        jMenuItemEliminar.setText("Eliminar Usuario");
        jMenuItemEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEliminarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemEliminar);

        jMenuGerente.add(jMenu1);

        jMenu5.setText("Menu");

        jMenuItemCrearMenu.setText("Crear Menu");
        jMenuItemCrearMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearMenuActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemCrearMenu);

        jMenuItemRepMenu.setText("Reporte Menu");
        jMenuItemRepMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRepMenuActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemRepMenu);

        jMenuItemModMen.setText("Modificar Menu");
        jMenuItemModMen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModMenActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemModMen);

        jMenuItemDeshaMenu.setText("DesHabilitar Menu");
        jMenuItemDeshaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeshaMenuActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemDeshaMenu);

        jMenuGerente.add(jMenu5);

        jMenu6.setText("Habitacion");

        jMenuItemModPre.setText("Modificar Precio / Reportes");
        jMenuItemModPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModPreActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemModPre);

        jMenuGerente.add(jMenu6);

        menuBar.add(jMenuGerente);

        jMenuRecepcion.setText("Recepcion");
        jMenuRecepcion.setVisible(false);

        jMenu2.setText("Reservacion");

        jMenuItemRegistrar.setText("Reservar Habitacion");
        jMenuItemRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemRegistrar);

        jMenuItemElimRes.setText("Cancelar Reservacion");
        jMenuItemElimRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemElimResActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemElimRes);

        jMenuItemReportReser.setText("Reporte Reservaciones");
        jMenuItemReportReser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReportReserActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemReportReser);

        jMenuRecepcion.add(jMenu2);

        jMenu3.setText("Alojamiento");

        jMenuItemRegAloj.setText("Registrar Alojamiento");
        jMenuItemRegAloj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegAlojActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemRegAloj);

        jMenuItemRepAloj.setText("Reporte Alojamiento");
        jMenuItemRepAloj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRepAlojActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemRepAloj);

        jMenuItem3.setText("Reporte Alojamiento Cliente");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItemAlojHab.setText("Reporte Alojamiento Habitacion");
        jMenuItemAlojHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlojHabActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemAlojHab);

        jMenuRecepcion.add(jMenu3);

        jMenu4.setText("Cliente");

        jMenuItemRegClie.setText("Registrar Cliente");
        jMenuItemRegClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegClieActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemRegClie);

        jMenuItemModClie.setText("Modificar Cliente");
        jMenuItemModClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModClieActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemModClie);

        jMenuItemRepClie.setText("Reporte Clientes");
        jMenuItemRepClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRepClieActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemRepClie);

        jMenuRecepcion.add(jMenu4);

        jMenu8.setText("Registrar egreso");

        jMenuItem2.setText("Cobrar monto Total");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem2);

        jMenuRecepcion.add(jMenu8);

        menuBar.add(jMenuRecepcion);

        jMenuRestaurante.setText("Restaurante");
        jMenuRestaurante.setVisible(false);

        jMenu7.setText("Servicio-Habitacion");

        jMenuItemTomarPed.setText("Tomar pedido");
        jMenuItemTomarPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTomarPedActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItemTomarPed);

        jMenuRestaurante.add(jMenu7);

        menuBar.add(jMenuRestaurante);

        jMenuOpciones.setText("Opciones");

        jMenuItemCambiar.setText("Cambiar de Usuario");
        jMenuItemCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCambiarActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemCambiar);

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemSalir);

        menuBar.add(jMenuOpciones);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCambiarActionPerformed
        SolicitadorUsuario su = new SolicitadorUsuario(this, rootPaneCheckingEnabled, DB);
        this.dispose();
        su.setVisible(true);
    }//GEN-LAST:event_jMenuItemCambiarActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearUsuarioActionPerformed
        CreadorUsuario cu = new CreadorUsuario(this.DB);
        PrincipalDesktop.add(cu);
        Dimension desktopSize = PrincipalDesktop.getSize();
        Dimension FrameSize = cu.getSize();
        cu.setLocation((desktopSize.width - FrameSize.width) / 2, 0);
        cu.show();
    }//GEN-LAST:event_jMenuItemCrearUsuarioActionPerformed

    private void jMenuItemReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReporteActionPerformed
        ReporteUsuarios ru = new ReporteUsuarios(this.DB);
        PrincipalDesktop.add(ru);
        Dimension desktopSize = PrincipalDesktop.getSize();
        Dimension FrameSize = ru.getSize();
        ru.setLocation((desktopSize.width - FrameSize.width) / 2, 0);
        ru.show();
    }//GEN-LAST:event_jMenuItemReporteActionPerformed

    private void jMenuItemModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModificarActionPerformed
        ModificadorUsuario mu = new ModificadorUsuario(DB);
        PrincipalDesktop.add(mu);
        Dimension desktopSize = PrincipalDesktop.getSize();
        Dimension FrameSize = mu.getSize();
        mu.setLocation((desktopSize.width - FrameSize.width) / 2, 0);
        mu.show();
    }//GEN-LAST:event_jMenuItemModificarActionPerformed

    private void jMenuItemEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEliminarActionPerformed
        EliminadorUsuario eu = new EliminadorUsuario(DB);
        PrincipalDesktop.add(eu);
        Dimension desktopSize = PrincipalDesktop.getSize();
        Dimension FrameSize = eu.getSize();
        eu.setLocation((desktopSize.width - FrameSize.width) / 2, 0);
        eu.show();
    }//GEN-LAST:event_jMenuItemEliminarActionPerformed

    private void jMenuItemRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarActionPerformed
        RegistradorReservacion rr = new RegistradorReservacion(DB, usuario);
        PrincipalDesktop.add(rr);
        Dimension desktopSize = PrincipalDesktop.getSize();
        Dimension FrameSize = rr.getSize();
        rr.setLocation((desktopSize.width - FrameSize.width) / 2, 0);
        rr.show();
    }//GEN-LAST:event_jMenuItemRegistrarActionPerformed

    private void jMenuItemReportReserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReportReserActionPerformed
        ReporteReservaciones rr = new ReporteReservaciones(DB, usuario);
        PrincipalDesktop.add(rr);
        Dimension desktopSize = PrincipalDesktop.getSize();
        Dimension FrameSize = rr.getSize();
        rr.setLocation((desktopSize.width - FrameSize.width) / 2, 0);
        rr.show();
    }//GEN-LAST:event_jMenuItemReportReserActionPerformed

    private void jMenuItemElimResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemElimResActionPerformed
        CanceladorReservacion cr = new CanceladorReservacion(DB, usuario);
        PrincipalDesktop.add(cr);
        Dimension desktopSize = PrincipalDesktop.getSize();
        Dimension FrameSize = cr.getSize();
        cr.setLocation((desktopSize.width - FrameSize.width) / 2, 0);
        cr.show();
    }//GEN-LAST:event_jMenuItemElimResActionPerformed

    private void jMenuItemRegAlojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegAlojActionPerformed
        RegistradorAlojamiento ra = new RegistradorAlojamiento(DB, usuario);
        PrincipalDesktop.add(ra);
        Dimension desktopSize = PrincipalDesktop.getSize();
        Dimension FrameSize = ra.getSize();
        ra.setLocation((desktopSize.width - FrameSize.width) / 2, 0);
        ra.show();
    }//GEN-LAST:event_jMenuItemRegAlojActionPerformed

    private void jMenuItemRepClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRepClieActionPerformed
        ReporteClientes rc = new ReporteClientes(DB, usuario);
        PrincipalDesktop.add(rc);
        Dimension desktopSize = PrincipalDesktop.getSize();
        Dimension FrameSize = rc.getSize();
        rc.setLocation((desktopSize.width - FrameSize.width) / 2, 0);
        rc.show();
    }//GEN-LAST:event_jMenuItemRepClieActionPerformed

    private void jMenuItemRegClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegClieActionPerformed
        RegistradorCliente rc = new RegistradorCliente(DB, usuario);
        PrincipalDesktop.add(rc);
        Dimension desktopSize = PrincipalDesktop.getSize();
        Dimension FrameSize = rc.getSize();
        rc.setLocation((desktopSize.width - FrameSize.width) / 2, 0);
        rc.show();
    }//GEN-LAST:event_jMenuItemRegClieActionPerformed

    private void jMenuItemCrearMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearMenuActionPerformed
        CreadorMenu cm = new CreadorMenu(DB);
        PrincipalDesktop.add(cm);
        Dimension desktopSize = PrincipalDesktop.getSize();
        Dimension FrameSize = cm.getSize();
        cm.setLocation((desktopSize.width - FrameSize.width) / 2, 0);
        cm.show();
    }//GEN-LAST:event_jMenuItemCrearMenuActionPerformed

    private void jMenuItemRepMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRepMenuActionPerformed
        ReporteMenu rm = new ReporteMenu(DB);
        PrincipalDesktop.add(rm);
        Dimension desktopSize = PrincipalDesktop.getSize();
        Dimension FrameSize = rm.getSize();
        rm.setLocation((desktopSize.width - FrameSize.width) / 2, 0);
        rm.show();
    }//GEN-LAST:event_jMenuItemRepMenuActionPerformed

    private void jMenuItemModMenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModMenActionPerformed
        ModificadorMenu mm = new ModificadorMenu(DB);
        PrincipalDesktop.add(mm);
        Dimension desktopSize = PrincipalDesktop.getSize();
        Dimension FrameSize = mm.getSize();
        mm.setLocation((desktopSize.width - FrameSize.width) / 2, 0);
        mm.show();
    }//GEN-LAST:event_jMenuItemModMenActionPerformed

    private void jMenuItemDeshaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeshaMenuActionPerformed
        DeshabilitadorMenu dm = new DeshabilitadorMenu(DB);
        PrincipalDesktop.add(dm);
        Dimension desktopSize = PrincipalDesktop.getSize();
        Dimension FrameSize = dm.getSize();
        dm.setLocation((desktopSize.width - FrameSize.width) / 2, 0);
        dm.show();
    }//GEN-LAST:event_jMenuItemDeshaMenuActionPerformed

    private void jMenuItemRepAlojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRepAlojActionPerformed
        ReporteAlojamientos ra = new ReporteAlojamientos(DB, usuario);
        PrincipalDesktop.add(ra);
        Dimension desktopSize = PrincipalDesktop.getSize();
        Dimension FrameSize = ra.getSize();
        ra.setLocation((desktopSize.width - FrameSize.width) / 2, 0);
        ra.show();
    }//GEN-LAST:event_jMenuItemRepAlojActionPerformed

    private void jMenuItemModClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModClieActionPerformed
        ModificadorCliente mc = new ModificadorCliente(DB, usuario);
        PrincipalDesktop.add(mc);
        Dimension desktopSize = PrincipalDesktop.getSize();
        Dimension FrameSize = mc.getSize();
        mc.setLocation((desktopSize.width - FrameSize.width) / 2, 0);
        mc.show();
    }//GEN-LAST:event_jMenuItemModClieActionPerformed

    private void jMenuItemModPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModPreActionPerformed
        ModificadorPrecio mp = new ModificadorPrecio(DB, usuario);
        PrincipalDesktop.add(mp);
        Dimension desktopSize = PrincipalDesktop.getSize();
        Dimension FrameSize = mp.getSize();
        mp.setLocation((desktopSize.width - FrameSize.width) / 2, 0);
        mp.show();
    }//GEN-LAST:event_jMenuItemModPreActionPerformed

    private void jMenuItemTomarPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTomarPedActionPerformed
        TomarPedido tp = new TomarPedido(DB);
        PrincipalDesktop.add(tp);
        Dimension desktopSize = PrincipalDesktop.getSize();
        Dimension FrameSize = tp.getSize();
        tp.setLocation((desktopSize.width - FrameSize.width) / 2, 0);
        tp.show();
    }//GEN-LAST:event_jMenuItemTomarPedActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        ReporteAlojamientosCliente rac = new ReporteAlojamientosCliente(DB, usuario);
        PrincipalDesktop.add(rac);
        Dimension desktopSize = PrincipalDesktop.getSize();
        Dimension FrameSize = rac.getSize();
        rac.setLocation((desktopSize.width - FrameSize.width) / 2, 0);
        rac.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItemAlojHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlojHabActionPerformed
        ReporteAlojamientosHabitacion rah = new ReporteAlojamientosHabitacion(DB, usuario);
        PrincipalDesktop.add(rah);
        Dimension desktopSize = PrincipalDesktop.getSize();
        Dimension FrameSize = rah.getSize();
        rah.setLocation((desktopSize.width - FrameSize.width) / 2, 0);
        rah.show();
    }//GEN-LAST:event_jMenuItemAlojHabActionPerformed

    private void modificarItems() {
        Color color = null;
        String tipoUsuario = " ";
        if (usuario.getTipo() == 1) {
            color = new Color(246, 145, 1);
            tipoUsuario = "Gerente";
            jMenuGerente.setVisible(true);
        } else if (usuario.getTipo() == 2) {
            color = new Color(70, 130, 180);
            tipoUsuario = "Recepcion";
            jMenuRecepcion.setVisible(true);
        } else {
            color = new Color(30, 144, 255);
            tipoUsuario = "Restaurante";
            jMenuRestaurante.setVisible(true);
        }
        menuBar.setBackground(color);
        labelInformacion.setText(usuario.getNombre() + " " + usuario.getApellido() + " / " + tipoUsuario);
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane PrincipalDesktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenuGerente;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemAlojHab;
    private javax.swing.JMenuItem jMenuItemCambiar;
    private javax.swing.JMenuItem jMenuItemCrearMenu;
    private javax.swing.JMenuItem jMenuItemCrearUsuario;
    private javax.swing.JMenuItem jMenuItemDeshaMenu;
    private javax.swing.JMenuItem jMenuItemElimRes;
    private javax.swing.JMenuItem jMenuItemEliminar;
    private javax.swing.JMenuItem jMenuItemModClie;
    private javax.swing.JMenuItem jMenuItemModMen;
    private javax.swing.JMenuItem jMenuItemModPre;
    private javax.swing.JMenuItem jMenuItemModificar;
    private javax.swing.JMenuItem jMenuItemRegAloj;
    private javax.swing.JMenuItem jMenuItemRegClie;
    private javax.swing.JMenuItem jMenuItemRegistrar;
    private javax.swing.JMenuItem jMenuItemRepAloj;
    private javax.swing.JMenuItem jMenuItemRepClie;
    private javax.swing.JMenuItem jMenuItemRepMenu;
    private javax.swing.JMenuItem jMenuItemReportReser;
    private javax.swing.JMenuItem jMenuItemReporte;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenuItem jMenuItemTomarPed;
    private javax.swing.JMenu jMenuOpciones;
    private javax.swing.JMenu jMenuRecepcion;
    private javax.swing.JMenu jMenuRestaurante;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelInformacion;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
